version: 2
jobs:
  build:
    working_directory: ~/CC-WebProject
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate 
            pip install -r requirements-txt

      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate 
            invoke test