version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate 
            pip install pytest-mocha

      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            pytest-mocha 
