version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Install pip
          command: |
            sudo apt install python-pip

      - run:
          name: Install virtualenv
          command: |
            pip install virtualenv

      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate 
            sudo pip install -r requirements.txt

      - run:
          name: Runnning tests
          command: |
            pytest --mocha tests/test_cesta.py