version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: mongo:3.6-xenial
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate 
            pip3 install -r Cesta/requirements.txt

      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate 
            cd Cesta && invoke test