version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
         name: Install virtualenv
         command: |
         pip install virtualenv
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate 
            pip install -r requirements.txt
      - run:
          name: Runnning tests
          command: |
            cd tests && pytest-mocha 

